import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Auth & Navigation
    'login_title': 'Secure Access Portal',
    'login_subtitle': 'Enter your credentials to access the defense grid',
    'email_label': 'Email Address',
    'password_label': 'Access Password',
    'sign_in': 'Initialize Session',
    'logging_in': 'Authenticating...',
    'restricted_access': 'Restricted Military/Academic Access Only',
    'login_error': 'Invalid identification. Access denied.',
    'logout': 'Terminate Session',
    'profile_settings': 'Profile & Identity',
    'dashboard': 'Control Center',
    'live_monitor': 'Intrusion Monitor',
    'traffic_analysis': 'Traffic Forensics',
    'vuln_scanner': 'Vuln Assessment',
    'malware_scanner': 'Malware Analysis',
    'research_doc': 'Research Proposal',
    'operational_overview': 'Operational Overview',
    'realtime_intrusion': 'Real-time Intrusion Monitoring',
    'batch_forensics': 'Batch Traffic Forensics',
    'vuln_assessment': 'Vulnerability Assessment',
    'malware_analysis_title': 'Advanced Malware Analysis',
    'project_doc': 'Research Documentation',
    'profile_title': 'Identity Management',
    'subtitle': 'Sudan Cyber Shield AI - Infrastructure Protection Grid',
    'demo_mode': 'PROTOTYPE / DEMO MODE',
    'select_theme': 'Select Theme',
    'lang_toggle': 'العربية',
    'access_denied': 'Access Denied',
    'access_denied_desc': 'Your current privilege level does not allow access to this module.',
    
    // Dashboard
    'host_info': 'Host Telemetry',
    'os_platform': 'OS Platform',
    'screen_res': 'Resolution',
    'logical_cores': 'Logical Cores',
    'system_resources': 'Resource Utilization',
    'cpu_usage': 'CPU',
    'ram_usage': 'RAM',
    'net_load': 'NETWORK',
    'real_network_monitor': 'Network Interface Monitoring',
    'online_status': 'Status',
    'connected': 'Online',
    'disconnected': 'Offline',
    'latency': 'Latency',
    'bandwidth': 'Est. Bandwidth',
    'connection_type': 'Comm Type',
    'status': 'Status',
    'uptime': 'Uptime',
    'threat_level': 'Threat Level',
    'attack_vector_dist': 'Detected Attack Vectors',
    'traffic_analysis_chart': 'Protocol Distribution',
    'recent_system_activity': 'Centralized Activity Logs',
    'user': 'Operator',
    'action': 'Action',
    'details': 'Operational Details',
    'timestamp': 'Timestamp',
    'sec_status_secure': 'SECURE',
    'sec_status_attack': 'UNDER ATTACK',

    // Scanners
    'scanner_title': 'Infrastructure Security Audit',
    'mode_simulated': 'Simulation Scan',
    'mode_file': 'Log Analysis',
    'target_infra': 'Critical Target Selection',
    'hospital_option': 'Omdurman Hospital Grid',
    'airport_option': 'Khartoum Int. Airport',
    'bank_option': 'Bank of Khartoum (Sim)',
    'local_network_option': 'Client Local Network',
    'upload_label': 'Upload Forensic Logs (CSV/LOG)',
    'start_scan': 'Initialize Audit',
    'analyze_file': 'Scan Log File',
    'scanning': 'Auditing Grid...',
    'analyzing_file': 'AI Logic Processing...',
    'net_monitor': 'Real-time Traffic Telemetry',
    'packet_rate': 'Packet Flow',
    'device_discovery': 'Active Device Discovery',
    'device_name': 'Alias',
    'ip_address': 'Local IP',
    'mac_address': 'Hardware Addr',
    'this_device': 'THIS HOST',
    'status_active': 'ACTIVE',
    'threat_intel': 'Live Threat Intel',
    'threat_high': 'CRITICAL',
    'threat_med': 'ELEVATED',
    'threat_low': 'NORMAL',
    'export_pcap': 'Export Traffic CSV',
    'generate_pdf': 'Generate PDF Audit',
    'report_generated': 'Assessment Report Ready',
    'critical_found': 'CRITICAL THREATS DETECTED',
    'download_report': 'Save Audit Report',

    // Malware
    'malware_title': 'VirusTotal Style Sandbox',
    'malware_desc': 'Upload binaries for deep heuristic analysis and multi-engine verification.',
    'choose_file': 'Select Binary',
    'start_deep_scan': 'Initialize Sandbox Analysis',
    'scan_artifact_strings': 'Extracted Artifact Strings',
    'analysis_complete': 'Deep Scan Finalized',
    'download_pdf_prompt': 'A high-fidelity forensic PDF is available for download.',

    // Traffic Batch
    'batch_title': 'Batch Log Forensic Analyzer',
    'batch_desc': 'Analyze large volumes of historical traffic logs to detect latent threats and exfiltration patterns.',
    'input_logs': 'Log Input Buffer',
    'capture_local': 'Capture Local Telemetry',
    'load_sample': 'Load Attack Sample',
    'paste_placeholder': 'Paste raw logs or CSV data here...',
    'analyze_btn': 'Analyze Log Batch',
    'analyzing_btn': 'Processing Logs...',
    'analysis_report': 'Forensic Analysis Result',
    'awaiting_data': 'System awaiting log input for processing.',
    'close': 'Dismiss',
    'download_pdf': 'Export PDF',
    'generating': 'Generating...',

    // Research Proposal
    'university': 'International University of Africa',
    'college': 'Faculty of Graduate Studies - Master Program (Computer Science)',
    'proposal_title': 'Research Proposal & System Documentation',
    'proposal_name': 'Designing an Intelligent System for Cyber Attack Detection and Vulnerability Assessment in Sudan’s Critical Infrastructure',
    'prepared_by': 'Prepared by / Mohammed Muzamil Al-Rayyes Ahmed',
    'intro': '1. Scientific Introduction',
    'problem': '2. Problem Statement',
    'objectives': '3. Research Objectives',
    'system_architecture': '4. System Architecture & Components',
    'tools': '5. Development Stack & Methodologies',
    'benefits': '6. Strategic Benefits & Significance',
    'analysis_models': '7. AI Analysis Models & Methodology',
    'diagram_label': 'System Functional Architecture Diagram',
    'intro_text': 'With the rapid digital transformation in Sudan, critical infrastructures such as airports, hospitals, and banks have become primary targets for sophisticated cyber threats. This research proposes "CyberShield AI", an integrated framework leveraging Large Language Models (LLMs) for predictive security.',
    'problem_text': 'Sudanese vital institutions suffer from a critical gap in early detection. Most existing solutions are black-box proprietary systems that lack transparency and the ability to adapt to local network behavioral patterns.',
    'traffic_engine_title': 'Cognitive Traffic Engine (Gemini 3 Pro/Flash)',
    'traffic_engine_desc': 'The system utilizes a dual-engine approach for traffic analysis. "Gemini 3 Flash" handles high-velocity real-time packet metadata analysis (DDoS detection, anomaly spikes), while "Gemini 3 Pro" is invoked for deep forensic analysis of suspicious flows.',
    'scan_logic_title': 'Heuristic Scanning & Deductive Reasoning',
    'scan_logic_desc': 'Unlike traditional signature-based scanners, this system employs "Cognitive Heuristics". It analyzes the "Intent" of code snippets and packet payloads to identify Zero-Day exploits.',
    'arch_dashboard': 'Intelligent Dashboard: Monitors host-level telemetry to detect resource exhaustion attacks in real-time.',
    'arch_ids': 'Live IDS Monitor: A deep packet inspection interface that visualizes network flows while utilizing AI to interpret payloads.',
    'arch_malware': 'Heuristic Malware Scanner: A hybrid analysis sandbox performing heuristic classification using Gemini 3 Pro.',
    'arch_batch': 'Batch Forensics: A post-incident analysis tool that processes massive historical logs.',
    'tools_text': 'The system is built using React.js and Google Gemini 3 API. It leverages browser-level Performance and Network APIs.',
    'benefits_text': '1) Proactive Defense. 2) Cost Efficiency. 3) Academic Contribution. 4) Data Sovereignty.',
    'diag_input': 'Data Ingestion',
    'diag_ai_core': 'AI Cognitive Core',
    'diag_output': 'Security Insights',
    'obj_1': 'Identify security vulnerabilities in simulated Sudanese infrastructures.',
    'obj_2': 'Develop a cognitive AI engine for interpreting complex behaviors.',
    'obj_3': 'Conduct simulated ethical tests to validate AI accuracy.',
    'obj_4': 'Establish unified forensic standards for local analysts.',
    'obj_5': 'Bridge academic research with industrial security needs.',

    // Profile
    'tab_overview': 'Account Overview',
    'tab_security': 'Access Security',
    'tab_activity': 'My Logs',
    'full_name': 'Full Legal Name',
    'role': 'Assigned Privilege',
    'department': 'Active Sector',
    'change_password': 'Update Access Key',
    'current_password': 'Current Password',
    'new_password': 'New Access Key',
    'confirm_password': 'Confirm New Key',
    'update_password': 'Apply Security Update',
    'password_success': 'Security key updated successfully.',
    'password_fail': 'Key mismatch or verification failed.',
    'user_management': 'Operator Control Panel',
    'add_user': 'Register Operator',
    'edit_user': 'Update Operator Identity',
    'save_changes': 'Confirm Changes',
    'cancel': 'Discard',
    'delete': 'Revoke Access',
    'tab_system_logs': 'System Core Logs',
    'import_logs': 'Ingest Logs',
    'export_logs': 'Extract Archives',
    'logs_imported': 'Log data ingested successfully.',
    'viewer_action_restricted': 'VIEWER ROLE: Action Restricted.',
    'upload_photo': 'Change Avatar',
    'activity_history': 'Recent Account Activity',
    'create_user': 'Create Operator',
    'leave_blank_pass': 'Leave blank to keep current password',
    'edit': 'Edit'
  },
  ar: {
    // Auth & Navigation
    'login_title': 'بوابة الوصول الآمن',
    'login_subtitle': 'يرجى إدخال بيانات الاعتماد للولوج إلى شبكة الدفاع',
    'email_label': 'عنوان البريد الإلكتروني',
    'password_label': 'كلمة مرور الوصول',
    'sign_in': 'بدء الجلسة',
    'logging_in': 'جاري المصادقة...',
    'restricted_access': 'دخول مقيد للجهات الأكاديمية والعسكرية فقط',
    'login_error': 'بيانات غير صحيحة. تم رفض الوصول.',
    'logout': 'إنهاء الجلسة',
    'profile_settings': 'الهوية والإعدادات',
    'dashboard': 'مركز التحكم',
    'live_monitor': 'مراقب التسلل',
    'traffic_analysis': 'التحليل الجنائي',
    'vuln_scanner': 'تقييم الثغرات',
    'malware_scanner': 'فحص البرمجيات',
    'research_doc': 'وثيقة البحث',
    'operational_overview': 'نظرة عامة على العمليات',
    'realtime_intrusion': 'المراقبة الفورية للتسلل',
    'batch_forensics': 'التحليل الجنائي المجمع للترافيك',
    'vuln_assessment': 'تقييم الثغرات الأمنية',
    'malware_analysis_title': 'التحليل المتقدم للبرمجيات الخبيثة',
    'project_doc': 'التوثيق الأكاديمي للبحث',
    'profile_title': 'إدارة الهوية الرقمية',
    'subtitle': 'درع السودان السيبراني الذكي - شبكة حماية البنى التحتية',
    'demo_mode': 'وضع العرض التجريبي / النموذج الأولي',
    'select_theme': 'اختر المظهر',
    'lang_toggle': 'English',
    'access_denied': 'تم رفض الوصول',
    'access_denied_desc': 'مستوى صلاحياتك الحالي لا يسمح بالوصول إلى هذا القسم.',

    // Dashboard
    'host_info': 'قياسات الجهاز المضيف',
    'os_platform': 'نظام التشغيل',
    'screen_res': 'دقة الشاشة',
    'logical_cores': 'الأنوية المنطقية',
    'system_resources': 'استهلاك موارد النظام',
    'cpu_usage': 'المعالج',
    'ram_usage': 'الذاكرة',
    'net_load': 'الشبكة',
    'real_network_monitor': 'مراقبة واجهات الشبكة الحقيقية',
    'online_status': 'الحالة',
    'connected': 'متصل',
    'disconnected': 'غير متصل',
    'latency': 'زمن الاستجابة',
    'bandwidth': 'العرض المقدر',
    'connection_type': 'نوع الاتصال',
    'status': 'حالة النظام',
    'uptime': 'مدة العمل',
    'threat_level': 'مستوى التهديد',
    'attack_vector_dist': 'توزيع نواقل الهجوم المكتشفة',
    'traffic_analysis_chart': 'توزيع البروتوكولات المكتشفة',
    'recent_system_activity': 'سجل النشاط المركزي',
    'user': 'المشغل',
    'action': 'الإجراء',
    'details': 'تفاصيل العمليات',
    'timestamp': 'الطابع الزمني',
    'sec_status_secure': 'آمن',
    'sec_status_attack': 'تحت الهجوم',

    // Scanners
    'scanner_title': 'التدقيق الأمني للبنية التحتية',
    'mode_simulated': 'فحص محاكاة',
    'mode_file': 'تحليل السجلات',
    'target_infra': 'اختيار الهدف الحيوي',
    'hospital_option': 'شبكة مستشفى أمدرمان',
    'airport_option': 'مطار الخرطوم الدولي',
    'bank_option': 'بنك الخرطوم (محاكاة)',
    'local_network_option': 'الشبكة المحلية للجهاز',
    'upload_label': 'رفع سجلات جنائية (CSV/LOG)',
    'start_scan': 'بدء التدقيق الأمني',
    'analyze_file': 'تحليل ملف السجل',
    'scanning': 'جاري التدقيق...',
    'analyzing_file': 'معالجة الذكاء الاصطناعي...',
    'net_monitor': 'قياسات الترافيك الفورية',
    'packet_rate': 'تدفق الحزم',
    'device_discovery': 'اكتشاف الأجهزة النشطة',
    'device_name': 'الاسم المستعار',
    'ip_address': 'العنوان الداخلي IP',
    'mac_address': 'عنوان العتاد MAC',
    'this_device': 'هذا الجهاز',
    'status_active': 'نشط',
    'threat_intel': 'ذكاء التهديدات الحي',
    'threat_high': 'خطير جداً',
    'threat_med': 'مرتفع',
    'threat_low': 'طبيعي',
    'export_pcap': 'تصدير ترافيك CSV',
    'generate_pdf': 'توليد تقرير PDF',
    'report_generated': 'تقرير التقييم جاهز',
    'critical_found': 'تم اكتشاف تهديدات حرجة',
    'download_report': 'حفظ تقرير التدقيق',

    // Malware
    'malware_title': 'صندوق رمل فحص البرمجيات',
    'malware_desc': 'رفع الملفات الثنائية للتحليل الاستدلالي العميق والتحقق عبر محركات متعددة.',
    'choose_file': 'اختر الملف',
    'start_deep_scan': 'بدء التحليل العميق',
    'scan_artifact_strings': 'النصوص المستخرجة من الملف',
    'analysis_complete': 'اكتمل التحليل العميق',
    'download_pdf_prompt': 'تم إنشاء تقرير جنائي بصيغة PDF متاح للتحميل الآن.',

    // Traffic Batch
    'batch_title': 'محلل السجلات الجنائية المجمع',
    'batch_desc': 'تحليل كميات ضخمة من سجلات الترافيك التاريخية لاكتشاف التهديدات الكامنة وأنماط تسريب البيانات.',
    'input_logs': 'ذاكرة إدخال السجلات',
    'capture_local': 'التقاط قياسات الجهاز',
    'load_sample': 'تحميل عينة هجوم',
    'paste_placeholder': 'قم بلصق السجلات الخام أو بيانات CSV هنا...',
    'analyze_btn': 'تحليل مجموعة السجلات',
    'analyzing_btn': 'جاري معالجة السجلات...',
    'analysis_report': 'نتائج التحليل الجنائي',
    'awaiting_data': 'النظام في انتظار إدخال السجلات لبدء المعالجة.',
    'close': 'إغلاق',
    'download_pdf': 'تصدير PDF',
    'generating': 'جاري التوليد...',

    // Research Proposal
    'university': 'جامعة إفريقيا العالمية',
    'college': 'كلية الدراسات العليا - برنامج الماجستير (علوم الحاسوب)',
    'proposal_title': 'وثيقة البحث العلمي وتوصيف النظام',
    'proposal_name': 'تصميم نظام ذكي لتقييم وكشف الهجمات السيبرانية على البنى التحتية الحرجة في السودان',
    'prepared_by': 'إعداد الطالب / محمد مزمل الريس أحمد',
    'intro': '1. المقدمة العلمية والمنهجية',
    'problem': '2. مشكلة البحث وأبعادها التقنية',
    'objectives': '3. أهداف البحث الاستراتيجية',
    'system_architecture': '4. بنية النظام ومكوناته التقنية',
    'tools': '5. الأدوات البرمجية ومنهجية التطوير',
    'benefits': '6. الفوائد العلمية والعملية للنظام',
    'analysis_models': '7. نماذج تحليل الذكاء الاصطناعي والمنهجية',
    'diagram_label': 'مخطط البنية الوظيفية المتكاملة للنظام',
    'intro_text': 'مع التحول الرقمي المتسارع في السودان، أصبحت البنى التحتية الحرجة أهدافاً رئيسية للهجمات المتطورة. يقترح هذا البحث نظام "درع السودان السيبراني الذكي"، وهو إطار عمل يدمج بين نماذج اللغات الضخمة (LLMs) وقياسات الشبكة الفورية.',
    'problem_text': 'تعاني المؤسسات الحيوية السودانية من فجوة في قدرات الاكتشاف المبكر. الحلول الحالية أنظمة مغلقة المصدر تفتقر للشفافية والقدرة على التكيف مع أنماط السلوك الشبكي المحلي.',
    'traffic_engine_title': 'محرك الترافيك المعرفي (Gemini 3 Pro/Flash)',
    'traffic_engine_desc': 'يعتمد النظام على نهج المحرك المزدوج؛ حيث يقوم "Gemini 3 Flash" بمعالجة البيانات الوصفية للحزم عالية السرعة، بينما يتم استدعاء "Gemini 3 Pro" للتحليل الجنائي العميق للتدفقات المشبوهة.',
    'scan_logic_title': 'الفحص الاستدلالي والاستنتاج المنطقي',
    'scan_logic_desc': 'على عكس الفواحص التقليدية القائمة على التواقيع، يستخدم هذا النظام "الاستدلال المعرفي" لتحليل "نية" الأكواد وحمولات الحزم لكشف ثغرات اليوم الصفر.',
    'arch_dashboard': 'لوحة التحكم الذكية: تراقب قياسات الجهاز المضيف لاكتشاف هجمات استنزاف الموارد في الوقت الحقيقي.',
    'arch_ids': 'مراقب التسلل الحي (IDS): واجهة لفحص الحزم العميقة تقوم بتصور تدفقات الشبكة مع استخدام الذكاء الاصطناعي لتفسير البيانات.',
    'arch_malware': 'ماسح البرمجيات الخبيثة الاستدلالي: صندوق رمل للتحليل الهجين يقوم بالتصنيف الاستدلالي باستخدام Gemini 3 Pro.',
    'arch_batch': 'التحليل الجنائي المجمع: أداة لتحليل ما بعد الحادثة تعالج السجلات التاريخية الضخمة.',
    'tools_text': 'تم بناء النظام باستخدام React.js ومحرك Google Gemini 3 كقلب معرفي. كما يعتمد على واجهات برمجة تطبيقات المتصفح لجمع القياسات.',
    'benefits_text': '1) الدفاع الاستباقي. 2) الكفاءة الاقتصادية. 3) المساهمة الأكاديمية. 4) السيادة الرقمية والوطنية.',
    'diag_input': 'مدخلات البيانات',
    'diag_ai_core': 'قلب الذكاء المعرفي',
    'diag_output': 'المخرجات الأمنية',
    'obj_1': 'تحديد وتحليل الثغرات الأمنية في بيئات محاكاة دقيقة للبنى التحتية السودانية.',
    'obj_2': 'تطوير محرك ذكاء اصطناعي معرفي قادر على تفسير السلوكيات الشبكية المعقدة.',
    'obj_3': 'إجراء اختبارات اختراق أخلاقية لمحاكاة سيناريوهات الهجمات وقياس دقة الاكتشاف.',
    'obj_4': 'إرساء معيار موحد للتقارير الجنائية السيبرانية للمحللين الأمنيين السودانيين.',
    'obj_5': 'تجسير الفجوة بين البحث الأكاديمي والتطبيق الصناعي والعملي في السودان.',

    // Profile
    'tab_overview': 'نظرة عامة على الحساب',
    'tab_security': 'أمن الوصول',
    'tab_activity': 'سجلاتي الشخصية',
    'full_name': 'الاسم الكامل الرسمي',
    'role': 'صلاحية الوصول',
    'department': 'القطاع النشط',
    'change_password': 'تحديث مفتاح الوصول',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'مفتاح الوصول الجديد',
    'confirm_password': 'تأكيد المفتاح الجديد',
    'update_password': 'تطبيق التحديث الأمني',
    'password_success': 'تم تحديث مفتاح الوصول بنجاح.',
    'password_fail': 'فشل التحديث. تأكد من صحة البيانات.',
    'user_management': 'لوحة تحكم المشغلين',
    'add_user': 'تسجيل مشغل جديد',
    'edit_user': 'تحديث هوية المشغل',
    'save_changes': 'تأكيد التغييرات',
    'cancel': 'إلغاء',
    'delete': 'سحب الصلاحيات',
    'tab_system_logs': 'سجلات نواة النظام',
    'import_logs': 'استيراد سجلات',
    'export_logs': 'استخراج الأرشيف',
    'logs_imported': 'تم استيراد بيانات السجلات بنجاح.',
    'viewer_action_restricted': 'صلاحية مشاهد: تم تقييد الإجراء.',
    'upload_photo': 'تغيير الصورة الشخصية',
    'activity_history': 'سجل نشاط الحساب الأخير',
    'create_user': 'إنشاء مشغل',
    'leave_blank_pass': 'اتركه فارغاً للاحتفاظ بكلمة المرور الحالية',
    'edit': 'تعديل'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');
  const t = (key: string) => translations[language][key] || key;
  const dir = language === 'ar' ? 'rtl' : 'ltr';
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};